[versions]
# -------------- Plugins -------------- #
agp = "8.7.3"
kotlin = "2.1.0"
navigationSafeArgsGradlePlugin = "2.8.6"

# -------------- Dependencies -------------- #
coreKtx = "1.15.0"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"

# Fragment Ktx
fragmentKtx = "1.8.9"

# Lifecycle
lifecycleRuntimeKtx = "2.9.4"

# Coroutines
coroutines = "1.9.0"

# Splash Screen Api
coreSplashscreen = "1.0.1"

# Navigational Components
navigationFragmentKtx = "2.8.6"
navigationUiKtx = "2.8.6"

# Dependency Injection -> Koin
koinAndroid = "4.0.2"

# Swipe Refresh Layout
swiperefreshlayout = "1.1.0"

# Lottie Animations
lottie = "6.6.2"
glide = "5.0.0-rc01"

# Media3 ExoPlayer
media3Exoplayer = "1.8.0"

# RecyclerView
recyclerview = "1.3.2"

# Firebase
firebaseCrashlyticsVersion = "20.0.3"
firebaseAnalyticsVersion = "23.0.0"
firebaseMessaging = "25.0.1"
firebaseConfig = "23.0.1"
firebasePerfVersion = "22.0.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgsGradlePlugin" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Splash Screen Api
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

# Navigational Components
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

# Dependency Injection -> Koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinAndroid" }
koin-core-coroutines = { group = "io.insert-koin", name = "koin-core-coroutines", version.ref = "koinAndroid" }


# Firebase
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlyticsVersion" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalyticsVersion" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebaseConfig" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebasePerfVersion" }

# Fragment Ktx
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }

# Lifecycle
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Swipe Refresh Layout
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

# Lottie Animations
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# Media3 ExoPlayer
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }

# RecyclerView
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }